### PR TITLE
Add interest and activity filters that display park results based off…

### PR DESCRIPTION
**Pull request by khaque1**
… what is selected

### CODE REVIEW

**Review by SnehaRajulapally — DISMISSED** [review]
Looks Good!

**Review by eprager — DISMISSED** [review]
Looks good!

**Review by eprager — APPROVED** [review]
Looks good!

**Review by missamcdonald — APPROVED** [review]
Looks Good!

**Review by SnehaRajulapally — APPROVED** [review]
Looks great!

**Pull request merged**
