### PR TITLE
Implement searching within a given radius

### PR DESCRIPTION
**Pull request by eprager**
Distance is calculated given a user provided location and compared against the latitudes and longitudes in the NPS database for national parks.   This distance is now also displayed below the park information.

### CODE REVIEW

**Review by khaque1 — DISMISSED** [review]
Awesome!

**Review by SnehaRajulapally — DISMISSED** [review]
Great Work!

**Review by khaque1 — APPROVED** [review]
Perfect

**Review by SnehaRajulapally — APPROVED** [review]
Looks Good!

**Review by missamcdonald — APPROVED** [review]
Looks great!

**Pull request merged**
