### PR TITLE
Update files with styling and checkbox dropdown options

### PR DESCRIPTION
**Pull request by SnehaRajulapally**
Update files with styling and checkbox dropdown options

### CODE REVIEW

**Review by missamcdonald — DISMISSED** [review]
Looks good!

**Review by khaque1 — DISMISSED** [review]

**Comment by khaque1** [comment]
Awesome!

**Review by eprager — APPROVED** [review]
Looks good

**Review by missamcdonald — APPROVED** [review]
Approved.

**Pull request merged**
